title: Dongjae Han
description: Physics, research, and programming notes

url: "https://dongjaehan.github.io"
baseurl: ""

timezone: Asia/Seoul

markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

permalink: /posts/:title/

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
